image: alpine/edge
secrets:
  - fb63ac90-8b81-4e80-aeba-3f4b728c26d5
tasks:
  - known_hosts: |
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - push: |
      cd config.nvim
      git remote add gh git@github.com:aidenlangley/config.nvim.git
      git push gh main
