require("extra.config.alpha")
require("extra.config.feline")
require("extra.config.gitsigns")
require("extra.config.indent_blankline")
require("extra.config.leap")
require("extra.config.mini")
require("extra.config.neo_tree")
require("extra.config.neogen")
require("extra.config.project")
require("extra.config.tidy")
require("extra.config.todo_comments")
require("extra.config.toggleterm")
require("extra.config.which_key")

require("extra.autocmds")
