require("mini.align").setup({})
require("mini.bufremove").setup({})
require("mini.comment").setup({})
require("mini.cursorword").setup({})
require("mini.pairs").setup({})
require("mini.surround").setup({})
require("mini.tabline").setup({})
