require("telescope").setup({
  pickers = {
    buffers = { theme = "dropdown" },
    builtin = { theme = "ivy" },
    command_history = { theme = "ivy" },
    commands = { theme = "ivy" },
    fd = { theme = "dropdown" },
    filetypes = { theme = "ivy" },
    git_branches = { theme = "dropdown" },
    git_commits = { theme = "ivy" },
    git_stash = { theme = "ivy" },
    grep_string = { theme = "ivy" },
    help_tags = { theme = "ivy" },
    highlights = { theme = "ivy" },
    jumplist = { theme = "dropdown" },
    live_grep = { theme = "ivy" },
    lsp_definitions = { theme = "ivy" },
    lsp_document_symbols = { theme = "ivy" },
    lsp_implementations = { theme = "ivy" },
    lsp_references = { theme = "ivy" },
    lsp_type_definitions = { theme = "ivy" },
    lsp_workspace_symbols = { theme = "ivy" },
    man_pages = { theme = "ivy" },
    projects = { theme = "dropdown" },
    registers = { theme = "ivy" },
    search_history = { theme = "ivy" },
    session_lens = { theme = "ivy" },
    treesitter = { theme = "ivy" },
    vim_options = { theme = "ivy" },
  },
})
