-- require("carbon").setup({
-- 	auto_open = false,
-- 	sidebar_width = 32,
-- 	highlights = {
-- 		CarbonDir = {
-- 			fg = "#7daea3",
-- 			bold = true,
-- 		},
-- 		CarbonFile = {
-- 			fg = "#ebdbb2",
-- 			bold = false,
-- 		},
-- 		CarbonSymlink = {
-- 			fg = "#d3869b",
-- 			bold = true,
-- 		},
-- 		CarbonBrokenSymLink = {
-- 			fg = "#b47109",
-- 			bold = true,
-- 		},
-- 		CarbonIndicator = {
-- 			fg = "#89786E",
-- 			bold = false,
-- 		},
-- 		CarbonDanger = {
-- 			fg = "#ea6962",
-- 			bold = true,
-- 		},
-- 		CarbonPending = {
-- 			fg = "#d8a657",
-- 			bold = true,
-- 		},
-- 		CarbonFlash = {
-- 			link = "Visual",
-- 		},
-- 	},
-- })
